### ISSUE TITLE
When disk is full, trying to attempt to save might lead to data loss

### ISSUE THREAD

**Issue by schrmh** [misobarisic/yoku#1]
I just added something to an existing list in yoku and tried to save it by exiting by using q.
yoku wasn't able to save, told me my disk is full, and overwrote my note.md file with a 0 byte file.
Possible solutions
- Keep a backup around.
- Perform the disk free check earlier and maybe prevent the user from quitting by using q until the user has enough disk space (to not lose new changes)

Using yoku version 0.1.1 on Arch (yoku-bin from AUR)

**Comment by misobarisic** [comment]
I apologize for this oversight. Fixing soon

**Comment by misobarisic** [comment]
New version released [v0.1.2](https://github.com/misobarisic/yoku/releases/tag/v0.1.2)

**Comment by schrmh** [comment]
Thanks, that was quick. It does keep the file intact now (provoked full disk situation again), new changes are thrown away however.

But I noticed that after running out of disk space once and then making space again, that it does not let me save after I added a new note entry by using o or a list entry by using l (creating new files itself by using u works however), I always get 
`
thread 'main' panicked at 'Could not write to file "/home/duda/.local/share/yoku/Backup.md"', src/lib/src/todo.rs:52:33                                                                         
                                                                                                                     note: run with `RUST_BACKTRACE=1` environment variable to display a backt
race
`

On another note, I think the PKGBUILD of yoku-bin in the AUR has a problem now. When I try to install it, it's not passing the sha256sums validity check on my system anymore. I switched to yoku-git for now.

**Comment by misobarisic** [comment]
`yoku-bin` works for me. Checksum check passes without an issue.

**Comment by schrmh** [comment]
Looks like the checksum thing is not a problem when I use `yay` instead of `paru`
However, I still have that other (main) problem I mentioned in the last comment.

**Comment by misobarisic** [comment]
I am not able to reproduce your issue. Did you try removing the files which were created when you ran out of space?

**Comment by schrmh** [comment]
Still happens, even after reinstalling which is pretty weird.
When I build 3332b7dce1a92a94943e14ec4263c7b0026a9d07 it works,
when I build from the newer commits, the problem occurs.

`RUST_BACKTRACE=full`:
```
                                               1:     0x5612e1a5a18e - <unknown>
                                                                                   2:     0x5612e1a361f5 - <unknown>
                                                                                                                       3:     0
x5612e1a3a1b5 - <unknown>
                            4:     0x5612e1a3b8bf - <unknown>
                                                                5:     0x5612e1a3b5fa - <unknown>
                                                                                                    6:     0x5612e1a3bfb8 - <un
known>
         7:     0x5612e1a3bd57 - <unknown>
                                             8:     0x5612e1a3a89c - <unknown>
                                                                                 9:     0x5612e1a3ba72 - <unknown>
                                                                                                                    10:     0x5
612e1932383 - <unknown>
                         11:     0x5612e19f3d9e - <unknown>
                                                             12:     0x5612e19f186e - <unknown>
                                                                                                 13:     0x5612e1940b91 - <unkn
own>
      14:     0x5612e193e99f - <unknown>
                                          15:     0x5612e1943243 - <unknown>
                                                                              16:     0x5612e1938809 - <unknown>
                                                                                                                  17:     0x561
2e1a31aab - <unknown>
                       18:     0x5612e193f375 - <unknown>
                                                           19:     0x7f5c8bb55290 - <unknown>
                                                                                               20:     0x7f5c8bb5534a - __libc_
start_main
            21:     0x5612e1932775 - <unknown>
                                                22:                0x0 - <unknown>

```
